//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apply.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.Applicant_Professions = new HashSet<Applicant_Professions>();
        }
    
        public string ForeName { get; set; }
        public string SurName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Title { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> SalutationId { get; set; }
        public Nullable<int> CVId { get; set; }
        public string CreatedById { get; set; }
        public string ModifiedById { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ApplicantId { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Professions> Applicant_Professions { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CV CV { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Salutation Salutation { get; set; }
    }
}
